name: Publish
on:
  push:
    tags:  # trigger the publish job on tag creation
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    name: publish
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}