name: Publish
on:
  push:
    tags:  # trigger the publish job on tag creation
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    name: publish
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24 with JavaFX
        uses: actions/setup-java@v3
        with:
            java-version: '24'
            distribution: 'zulu'
            java-package: 'jdk+fx'
            cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}